name: Build, Test, Lint
on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enable Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: ./.github/templates/setup-pnpm

      - name: TypeCheck
        run: tsc -b

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
